data:extend({
	{
		type = "item",
		flags = {},
		subgroup = "uranium-products",
		order = "h[uranium]",
		stack_size = 1,
		name = "fuel-assembly-01",
		icon = "__UraniumPowerRemastered__/graphics/icons/fuel-assembly-01.png",
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-products",
		order = "h[uranium]",
		stack_size = 1,
		name = "fuel-assembly-02",
		icon = "__UraniumPowerRemastered__/graphics/icons/fuel-assembly-02.png",
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-products",
		order = "h[uranium]",
		stack_size = 1,
		name = "fuel-assembly-03",
		icon = "__UraniumPowerRemastered__/graphics/icons/fuel-assembly-03.png",
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-products",
		order = "h[uranium]",
		stack_size = 1,
		name = "fuel-assembly-04",
		icon = "__UraniumPowerRemastered__/graphics/icons/fuel-assembly-04.png",
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-products",
		order = "h[uranium]",
		stack_size = 1,
		name = "fuel-assembly-05",
		icon = "__UraniumPowerRemastered__/graphics/icons/fuel-assembly-05.png",
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-products",
		order = "h[uranium]",
		stack_size = 1,
		name = "fuel-assembly-06",
		icon = "__UraniumPowerRemastered__/graphics/icons/fuel-assembly-06.png",
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-products",
		order = "h[uranium]",
		stack_size = 1,
		name = "fuel-assembly-07",
		icon = "__UraniumPowerRemastered__/graphics/icons/fuel-assembly-07.png",
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-products",
		order = "h[uranium]",
		stack_size = 1,
		name = "fuel-assembly-08",
		icon = "__UraniumPowerRemastered__/graphics/icons/fuel-assembly-08.png",
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-products",
		order = "h[uranium]",
		stack_size = 1,
		name = "fuel-assembly-09",
		icon = "__UraniumPowerRemastered__/graphics/icons/fuel-assembly-09.png",
	},
	{
		type = "item",
		name = "fuel-assembly-10",
		icon = "__UraniumPowerRemastered__/graphics/icons/fuel-assembly-10.png",
		icon_size = 32,
		flags = {},
		subgroup = "uranium-products",
		order = "h[uranium]",
		fuel_category = "nuclear",
		burnt_result = "used-up-uranium-fuel-cell",
		fuel_value = "8GJ",
		stack_size = 1
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-products",
		order = "h[uranium]",
		stack_size = 1,
		name = "fuel-assembly-11",
		icon = "__UraniumPowerRemastered__/graphics/icons/recycling-assets/fuel-assembly-11.png",
	}
})
