data:extend({
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 100,
		name = "uranium-pellet-01",
		icon = "__UraniumPowerRemastered__/graphics/icons/uranium-pellet-01.png",
		icon_size = 32,
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 100,
		name = "uranium-pellet-02",
		icon = "__UraniumPowerRemastered__/graphics/icons/uranium-pellet-02.png",
		icon_size = 32,
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 100,
		name = "uranium-pellet-03",
		icon = "__UraniumPowerRemastered__/graphics/icons/uranium-pellet-03.png",
		icon_size = 32,
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 100,
		name = "uranium-pellet-04",
		icon = "__UraniumPowerRemastered__/graphics/icons/uranium-pellet-04.png",
		icon_size = 32,
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 100,
		name = "uranium-pellet-05",
		icon = "__UraniumPowerRemastered__/graphics/icons/uranium-pellet-05.png",
		icon_size = 32,
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 100,
		name = "uranium-pellet-06",
		icon = "__UraniumPowerRemastered__/graphics/icons/uranium-pellet-06.png",
		icon_size = 32,
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 100,
		name = "uranium-pellet-07",
		icon = "__UraniumPowerRemastered__/graphics/icons/uranium-pellet-07.png",
		icon_size = 32,
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 100,
		name = "uranium-pellet-08",
		icon = "__UraniumPowerRemastered__/graphics/icons/uranium-pellet-08.png",
		icon_size = 32,
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 100,
		name = "uranium-pellet-09",
		icon = "__UraniumPowerRemastered__/graphics/icons/uranium-pellet-09.png",
		icon_size = 32,
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 100,
		name = "uranium-pellet-10",
		icon = "__UraniumPowerRemastered__/graphics/icons/uranium-pellet-10.png",
		icon_size = 32,
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 100,
		name = "uranium-dioxide",
		icon = "__UraniumPowerRemastered__/graphics/icons/recycling-assets/uo2.png",
		icon_size = 32,
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 100,
		name = "plutonium-dioxide",
		icon = "__UraniumPowerRemastered__/graphics/icons/recycling-assets/puo2.png",
		icon_size = 32,
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 100,
		name = "uranium-pellet-11",
		icon = "__UraniumPowerRemastered__/graphics/icons/recycling-assets/mox-pellet.png",
		icon_size = 32,
	},
	{
		type = "item",
		flags = {},
		subgroup = "uranium-intermediate-product",
		order = "f[uranium]",
		stack_size = 10,
		name = "waste-glass",
		icon = "__UraniumPowerRemastered__/graphics/icons/recycling-assets/waste-glass.png",
		icon_size = 32,
	},
})
